version: '{build}'
branches:
  only:
  - feature/nuget
image: Visual Studio 2019
init:
- cmd: set GITVERSION_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build:
  project: build/FLExBridge.proj
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
test: off
artifacts:
- path: output/*nupkg
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
